# Generated by Django 4.2.5 on 2023-09-06 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelTable(
            name="category",
            table="product_category",
        ),
    ]
