# Generated by Django 4.2.5 on 2023-09-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_category_options_alter_category_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
